[package]
name = "driver"
version = "1.0.0"
edition = "2021"

[dependencies]
redis = { version = "0.19.0", features = ["tokio-comp"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
