[package]
name = "port"
version = "1.0.0"
edition = "2021"

[dependencies]
futures = "0.3"
async-trait = "0.1.51"
anyhow = "1.0"
actix = "0.12"

# Internal Dependencies
domain = { path = "../domain" }
